[default]
dburl = 'postgresql://service=moma'
pgconnstring = 'user=moma dbname=moma port=5432 host=0.0.0.0 password=marmol'
momadir = '/home/vagrant/pds-2019'
momadirdata = '/home/vagrant/pds-2019/data2'